/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout/route'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSalesDocumentsImport } from './routes/_layout/sales/documents'
import { Route as LayoutProductsInventoryImport } from './routes/_layout/products/inventory'
import { Route as LayoutappSettingsImport } from './routes/_layout/(app)/settings'

// Create/Update Routes

const LayoutRouteRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutSalesDocumentsRoute = LayoutSalesDocumentsImport.update({
  id: '/sales/documents',
  path: '/sales/documents',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutProductsInventoryRoute = LayoutProductsInventoryImport.update({
  id: '/products/inventory',
  path: '/products/inventory',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutappSettingsRoute = LayoutappSettingsImport.update({
  id: '/(app)/settings',
  path: '/settings',
  getParentRoute: () => LayoutRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/(app)/settings': {
      id: '/_layout/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutappSettingsImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/products/inventory': {
      id: '/_layout/products/inventory'
      path: '/products/inventory'
      fullPath: '/products/inventory'
      preLoaderRoute: typeof LayoutProductsInventoryImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/sales/documents': {
      id: '/_layout/sales/documents'
      path: '/sales/documents'
      fullPath: '/sales/documents'
      preLoaderRoute: typeof LayoutSalesDocumentsImport
      parentRoute: typeof LayoutRouteImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutappSettingsRoute: typeof LayoutappSettingsRoute
  LayoutProductsInventoryRoute: typeof LayoutProductsInventoryRoute
  LayoutSalesDocumentsRoute: typeof LayoutSalesDocumentsRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutappSettingsRoute: LayoutappSettingsRoute,
  LayoutProductsInventoryRoute: LayoutProductsInventoryRoute,
  LayoutSalesDocumentsRoute: LayoutSalesDocumentsRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/settings': typeof LayoutappSettingsRoute
  '/products/inventory': typeof LayoutProductsInventoryRoute
  '/sales/documents': typeof LayoutSalesDocumentsRoute
}

export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/settings': typeof LayoutappSettingsRoute
  '/products/inventory': typeof LayoutProductsInventoryRoute
  '/sales/documents': typeof LayoutSalesDocumentsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/(app)/settings': typeof LayoutappSettingsRoute
  '/_layout/products/inventory': typeof LayoutProductsInventoryRoute
  '/_layout/sales/documents': typeof LayoutSalesDocumentsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/settings' | '/products/inventory' | '/sales/documents'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/products/inventory' | '/sales/documents'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/_layout/(app)/settings'
    | '/_layout/products/inventory'
    | '/_layout/sales/documents'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout/route.tsx",
      "children": [
        "/_layout/",
        "/_layout/(app)/settings",
        "/_layout/products/inventory",
        "/_layout/sales/documents"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/(app)/settings": {
      "filePath": "_layout/(app)/settings.tsx",
      "parent": "/_layout"
    },
    "/_layout/products/inventory": {
      "filePath": "_layout/products/inventory.tsx",
      "parent": "/_layout"
    },
    "/_layout/sales/documents": {
      "filePath": "_layout/sales/documents.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
